// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: copyfrom.go

package sqlc

import (
	"context"
)

// iteratorForCreateTrades implements pgx.CopyFromSource.
type iteratorForCreateTrades struct {
	rows                 []CreateTradesParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateTrades) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateTrades) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].Hour,
		r.rows[0].Date,
		r.rows[0].Ticker,
		r.rows[0].Price,
		r.rows[0].Quantity,
	}, nil
}

func (r iteratorForCreateTrades) Err() error {
	return nil
}

func (q *Queries) CreateTrades(ctx context.Context, arg []CreateTradesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"trades"}, []string{"hour", "date", "ticker", "price", "quantity"}, &iteratorForCreateTrades{rows: arg})
}
