// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Trade struct {
	ID        int32
	Hour      string
	Date      pgtype.Date
	Ticker    string
	Price     pgtype.Numeric
	Quantity  int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
