// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreateTrades(ctx context.Context, arg []CreateTradesParams) (int64, error)
	ListTradeInfoByTickerAndDate(ctx context.Context, arg ListTradeInfoByTickerAndDateParams) ([]ListTradeInfoByTickerAndDateRow, error)
}

var _ Querier = (*Queries)(nil)
